language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django==1.5"
  - DJANGO="django==1.6"
  - DJANGO="https://www.djangoproject.com/download/1.7b4/tarball/"

install:
  - pip install psycopg2
  - pip install $DJANGO
  - pip install coverage coveralls

script:
  - coverage run --source=django_nopassword setup.py test
  - coverage report


before_script:
  - psql -c 'create database django_nopassword;' -U postgres

after_success: coveralls
